### ISSUE TITLE
Using python 3.10 on linux ubuntu

### ISSUE THREAD

**Issue by ArshCypherZ** [regebro/tzlocal#134]
Error:
keyerror "cron"
pkg_resources.DistributionNotFound:
backports.zoneinfo; python_version , "3.9"
{'tzlocal'}

**Comment by regebro** [comment]
I can't reproduce this.

**Comment by irfanhakim-as** [comment]
I'm aware this issue is closed and that I could open up a new one, but I decided against it since I don't think this is applicable/relevant to newer versions of this package - but I did encounter this issue on Python 3.8.10/Pip 25.0.1.

The full error I received:

<details>
<summary>Traceback</summary>

```
apscheduler Traceback (most recent call last):
apscheduler   File "/venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 900, in _create_plugin_instance
apscheduler     plugin_cls = class_container[alias]
apscheduler KeyError: 'cron'
apscheduler
apscheduler During handling of the above exception, another exception occurred:
apscheduler
apscheduler Traceback (most recent call last):
apscheduler   File "manage.py", line 23, in <module>
apscheduler     main()
apscheduler   File "manage.py", line 19, in main
apscheduler     execute_from_command_line(sys.argv)
apscheduler   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
apscheduler     utility.execute()
apscheduler   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
apscheduler     django.setup()
apscheduler   File "/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
apscheduler     apps.populate(settings.INSTALLED_APPS)
apscheduler   File "/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
apscheduler     app_config.ready()
apscheduler   File "/base/base/apps.py", line 9, in ready
apscheduler     tasks.start()
apscheduler   File "/base/base/tasks.py", line 17, in start
apscheduler     scheduler.add_job(clean_data, "cron", id=job_name, replace_existing=True, hour="0", minute="0", second="0")
apscheduler   File "/venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 424, in add_job
apscheduler     'trigger': self._create_trigger(trigger, trigger_args),
apscheduler   File "/venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 925, in _create_trigger
apscheduler     return self._create_plugin_instance('trigger', trigger, trigger_args)
apscheduler   File "/venv/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 903, in _create_plugin_instance
apscheduler     plugin_cls = class_container[alias] = plugin_container[alias].load()
apscheduler   File "/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in load
apscheduler     self.require(*args, **kwargs)
apscheduler   File "/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in require
apscheduler     items = working_set.resolve(reqs, env, installer, extras=self.extras)
apscheduler   File "/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
apscheduler     raise DistributionNotFound(req, requirers)
apscheduler pkg_resources.DistributionNotFound: The 'backports.zoneinfo; python_version < "3.9"' distribution was not found and is required by tzlocal
```

</details>

In my case, my project is dependent on APScheduler:

```
APScheduler==3.10.1
├── pytz [required: Any, installed: 2023.3.post1]
├── setuptools [required: >=0.7, installed: 56.0.0]
├── six [required: >=1.4.0, installed: 1.16.0]
└── tzlocal [required: >=2.0,!=3.*, installed: 5.2]
    └── backports.zoneinfo [required: Any, installed: 0.2.1]
```

which in turn depends on `tzlocal` (5.2), that depends on `backports.zoneinfo` (0.2.1).

The issue stems from the L28 in `tzlocal` version 5.2's `pyproject.toml file:

```toml
dependencies = [
    "backports.zoneinfo; python_version < '3.9'",
    "tzdata; platform_system == 'Windows'",
]
```

This wasn't an issue before on my project's Ubuntu (variant) container, but stumbled upon this recently while porting my project to an Alpine-based container (using the same Python version, etc.), whereby for some reason, even though `pip freeze` returns the expected package name/version installed:

```
backports.zoneinfo==0.2.1
```

`pkg_resources` saw the `backports.zoneinfo` package as a different (normalised) name, namely, `backports-zoneinfo`:

```sh
# python3 -c "import pkg_resources; print([d.project_name for d in pkg_resources.working_set if d.project_name.startswith('backports')])"
['backports-zoneinfo']
```

Hence, the `pkg_resources` error that we receive due to `tzlocal` requiring, specifically, `backports.zoneinfo` (with a period, rather than a hyphen), since for whatever reason even though the right package was installed - its name was changed or seen differently:

```sh
pkg_resources.DistributionNotFound: The 'backports.zoneinfo; python_version < "3.9"' distribution was not found and is required by tzlocal
```

This is most certainly not an issue with `tzlocal`, and most definitely does not affect newer versions since I'm sure past Python 3.9, `backports.zoneinfo` is no longer needed, but I was able to work around this issue by adding the following symlink in my container:

```sh
ln -sf /venv/lib/python3.8/site-packages/backports_zoneinfo-0.2.1.dist-info /venv/lib/python3.8/site-packages/backports.zoneinfo-0.2.1.dist-info
```

Doing so allows `pkg_resources` to find the package, rightly, as `backports.zoneinfo` for `tzlocal`:

```sh
# python3 -c "import pkg_resources; print([d.project_name for d in pkg_resources.working_set if d.project_name.startswith('backports')])"
['backports.zoneinfo', 'backports-zoneinfo']
```

```sh
# python3 -c "import pkg_resources; print(pkg_resources.get_distribution('backports.zoneinfo'))"
backports.zoneinfo 0.2.1
```

I'm not sure where in the Python/Dependency management stack would've been responsible for normalising the `backports.zoneinfo` name to `backports-zoneinfo`, as I seem to have seen other instances of similar name "normalisations" too like `typing-extensions` becoming `typing_extensions`, etc. (not sure if related or not).

All in all, I hope anyone on the same boat that might find this would be able to work around it this way.

**Comment by regebro** [comment]
Yeah, that's strange, the name should be normalized in all cases, not sure why it didn't work here. Possibly that's some bad luck with different versions of pkg.resources and setuptools and pip interacting in a weird way, or something.
