### ISSUE TITLE
get_localzone() fails on Mac OS X 10.11 El Capitan with TypeError

### ISSUE THREAD

**Issue by dburr** [regebro/tzlocal#32]
Mac OS X 10.11.3 El Capitan
Python 3.5.1
tzlocal 1.2.1

Calls to `get_localzone()` fail with `TypeError: a bytes-like object is required, not 'str'`

I tracked this down to the call to `systemsetup -gettimezone` in `darwin.py`. Running this command in a terminal window gives an error stating that admin rights are required. I suspect this error message (which is being sent to `stdout`) is throwing off the code. Commenting out the call to `systemsetup -gettimezone` in `darwin.py` and falling back on checking the `/etc/localtime` symlink appears to work.

**Comment by xabbu137** [comment]
Hi - I had filed something similar yesterday - see [#30](https://github.com/regebro/tzlocal/issues/30).
And it was already fixed in the most recent version! Thanks to the maintainers for the quick resolve!
It really had to do with python 3 (as it worked on python 2), despite the change in permissions to `systemsetup -gettimezone`.

**Comment by regebro** [comment]
I just released 1.2.2, see if that works.

**Comment by xabbu137** [comment]
Cool - works for me (python 3.5.1, Mac OSX 10.11.3) - thanks a lot for the quick fix!
